# Numpy
Basics vectorized calculations

In [130]:
import numpy as np

## Generating Numbers

In [131]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
# Random 2x3 array
np.random.randn(2, 3)

array([[-0.85512918, -0.82033921,  0.22368572],
       [-0.75631634, -1.3160472 ,  0.35719417]])

In [133]:
# Create from python array
np.array([1,2,3])

array([1, 2, 3])

In [134]:
# Create zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [135]:
# Create ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [136]:
# Create identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [137]:
# Reshape
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [138]:
# Transpose
np.arange(15).reshape(3,5).T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

## Query Data Types

In [139]:
zeros23 = np.zeros((2,3))

In [140]:
zeros23.ndim

2

In [141]:
zeros23.shape

(2, 3)

In [142]:
zeros23.dtype

dtype('float64')

## Index and Slice
Just like python list, but not a copy

In [143]:
arr = np.arange(10)

In [144]:
arr[3], arr[:3], arr[-1]

(3, array([0, 1, 2]), 9)

In [145]:
sub_arr = arr[4:6]
sub_arr

array([4, 5])

In [146]:
# Changes to the slice applies to the array
sub_arr[:] = 10
arr

array([ 0,  1,  2,  3, 10, 10,  6,  7,  8,  9])

In [147]:
# Copy
np.arange(2).copy()

array([0, 1])

Higher dimension array address

In [148]:
arr_2d = np.array([[0,1],[2,3]])
arr_2d

array([[0, 1],
       [2, 3]])

In [149]:
arr_2d[0][1], arr_2d[0,1]

(1, 1)

Slicing multidimensional Array

In [150]:
arr33 = np.array([ 
    [1,2,3], 
    [4,5,6], 
    [7,8,9] 
])
arr33

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [151]:
# slice row 
arr33[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [152]:
# slice row and col
arr33[:2, 1:]

array([[2, 3],
       [5, 6]])

In [153]:
# slice only col

In [154]:
arr33[:,1]

array([2, 5, 8])

## Boolean Select

In [155]:
r = np.arange(10)
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
# Math operation on numpy array are pairwise
r % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [157]:
# Use numpy boolean array to select entry
r[r%2 == 0]

array([0, 2, 4, 6, 8])

### Boolean Logic in Selection

In [158]:
# Not
r[~(r%2 == 0)]

array([1, 3, 5, 7, 9])

In [159]:
# And
r[(r%3 == 0) & (r%2 == 0)]

array([0, 6])

In [160]:
# Or
r[(r%3 == 0) | (r%2 == 0)]

array([0, 2, 3, 4, 6, 8, 9])

### Array Selection
This always copy to new array

In [161]:
# Whole array
aSelect = np.arange(36).reshape(6,6)
aSelect

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [162]:
# Select specific row
aSelect[ [1,3] ]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [163]:
# Select elements [ [x1,x2],[y1,y2] ]
aSelect[ [1,3], [1,3] ]

array([ 7, 21])

## Compute


In [164]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
np.sqrt(c)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [166]:
np.exp(c)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [167]:
np.power(c,2), c ** 2

(array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81]),
 array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81]))

In [168]:
np.power(c,c), c ** c

(array([        1,         1,         4,        27,       256,      3125,
            46656,    823543,  16777216, 387420489]),
 array([        1,         1,         4,        27,       256,      3125,
            46656,    823543,  16777216, 387420489]))

In [169]:
np.ceil(c), np.floor(c), np.rint(c), np.sign(c)

(array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [170]:
# Get both integer and fraction
dm = np.random.randn(10)*3
dm

array([-2.54524054,  1.82705142, -3.66255448, -3.24703325, -1.8640912 ,
       -0.21401834, -3.50437776, -1.0999297 , -7.51126426,  2.19556574])

In [171]:
# Return tuple of two
np.modf(dm)

(array([-0.54524054,  0.82705142, -0.66255448, -0.24703325, -0.8640912 ,
        -0.21401834, -0.50437776, -0.0999297 , -0.51126426,  0.19556574]),
 array([-2.,  1., -3., -3., -1., -0., -3., -1., -7.,  2.]))