# Numpy
Basics vectorized calculations

In [2]:
import numpy as np

## Generating Numbers

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Random 2x3 array
np.random.randn(2, 3)

array([[-0.35673627,  0.11508126,  1.09450264],
       [ 0.13777578, -0.53312089,  0.94129318]])

In [5]:
# Create from python array
np.array([1,2,3])

array([1, 2, 3])

In [6]:
# Create zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# Create ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
# Create identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Query Data Types

In [9]:
zeros23 = np.zeros((2,3))

In [10]:
zeros23.ndim

2

In [11]:
zeros23.shape

(2, 3)

In [12]:
zeros23.dtype

dtype('float64')

## Index and Slice
Just like python list, but not a copy

In [13]:
arr = np.arange(10)

In [18]:
arr[3], arr[:3], arr[-1]

(3, array([0, 1, 2]), 9)

In [21]:
sub_arr = arr[4:6]
sub_arr

array([4, 5])

In [23]:
# Changes to the slice applies to the array
sub_arr[:] = 10
arr

array([ 0,  1,  2,  3, 10, 10,  6,  7,  8,  9])

In [24]:
# Copy
np.arange(2).copy()

array([0, 1])

Higher dimension array address

In [26]:
arr_2d = np.array([[0,1],[2,3]])
arr_2d

array([[0, 1],
       [2, 3]])

In [29]:
arr_2d[0][1], arr_2d[0,1]

(1, 1)