# Numpy
Basics vectorized calculations

In [1]:
import numpy as np

## Generating Numbers

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Random 2x3 array
np.random.randn(2, 3)

array([[-0.9078076 , -0.94923049, -0.59408868],
       [ 0.18448241, -0.93223584,  0.15630392]])

In [6]:
# Create from python array
np.array([1,2,3])

array([1, 2, 3])

In [8]:
# Create zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# Create ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# Create identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Query Data Types

In [19]:
zeros23 = np.zeros((2,3))

In [20]:
zeros23.ndim

2

In [21]:
zeros23.shape

(2, 3)

In [22]:
zeros23.dtype

dtype('float64')